---
  - name: User Management
    hosts: "{{ group }}"
    gather_facts: "{{ gather_facts }}"
    vars_files:
      - "../variables/addusers-values.yaml"
    tasks:
# Task for user 1 - values defined in ../variables/addusers-values.yaml
      - name: User1
        user: 
          name: "{{ user_name1 }}"
          uid: "{{ user1_uid }}"
# Task for user 2 - values defined in ../variables/addusers-values.yaml
      - name: User2
        user:
          name: "{{ user_name2 }}"
          uid: "{{ user2_uid }}"