---
 - name: apache installation
   hosts: dev-servers
   tasks:
     - name: install apache
       yum:
         name: httpd
         state: latest

     - name: start apache on CentOS 6
       when: ansible_distribution_major_version == "6"
       service:
         name: httpd
         state: started
         enabled: yes

     - name: start apache on CentOS 7
       when: ansible_distribution_major_version == "7"
       systemd:
         name: httpd
         state: started
         enabled: yes  

