---
  - name: This playbook will chack free disk in remote hosts
    hosts: "{{ group }}"
    tasks:
      - name: Check free disk
        when: ansible_distribution=="CentOS" and ansible_distribution_major_version=="7"
        command: df -h
        register: df_check
  
      - debug: var=df_check